# Generated by Django 4.2.17 on 2025-05-15 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localization', '0008_countrymodel_amount'),
        ('payments', '0002_alter_tenantpaymentmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantpaymentmodel',
            name='country',
            field=models.ForeignKey(blank=True, help_text='Country whose pricing was used for this payment', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenant_payments', to='localization.countrymodel'),
        ),
    ]
