# Generated by Django 4.2.17 on 2025-02-23 18:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('landlord', '0030_rename_landlordpropertyverificationdocumenttypemodel_landlorddocumenttypemodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandlordAvailabilityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landlord_availabilities', to='landlord.landlorddetailsmodel')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_availabilities', to='landlord.landlordpropertydetailsmodel')),
            ],
            options={
                'unique_together': {('landlord', 'property', 'date')},
            },
        ),
        migrations.CreateModel(
            name='LandlordAvailabilitySlotModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('max_meetings', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('availability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='landlord_availability.landlordavailabilitymodel')),
            ],
        ),
    ]
