# Generated by Django 4.2.17 on 2025-02-26 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landlord_availability', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landlordavailabilityslotmodel',
            name='max_meetings',
        ),
    ]
