# Generated by Django 4.2.17 on 2025-01-01 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('language_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllStaticStringsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strings', models.JSONField(default=dict, help_text='All static strings in specified language.')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='static_strings', to='language_data.languagemodel')),
            ],
        ),
    ]
