# Generated by Django 4.2.17 on 2025-01-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("localization", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="citiesmodel",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="citiesmodel",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="countriesdialcodemodel",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="countriesdialcodemodel",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="countriesmodel",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="countriesmodel",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="statesmodel",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="statesmodel",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
