# Generated by Django 4.2.17 on 2025-02-11 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localization', '0002_citiesmodel_is_active_citiesmodel_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='countriesmodel',
            name='currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='countriesmodel',
            name='currency_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='countriesmodel',
            name='currency_symbol',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
