# Generated by Django 4.2.17 on 2025-02-11 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0021_alter_landlordpropertydetailsmodel_property_city'),
        ('tenant', '0005_alter_tenantpersonalitydetailsmodel_country'),
        ('localization', '0004_citymodel_countrymodel_countrytranslationmodel_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CitiesModel',
        ),
        migrations.DeleteModel(
            name='CountriesDialCodeModel',
        ),
        migrations.DeleteModel(
            name='CountriesModel',
        ),
        migrations.DeleteModel(
            name='StatesModel',
        ),
        migrations.AddField(
            model_name='timezonemodel',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timezones', to='localization.countrymodel'),
        ),
        migrations.AddField(
            model_name='statemodel',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='localization.countrymodel'),
        ),
        migrations.AddField(
            model_name='countrytranslationmodel',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='localization.countrymodel'),
        ),
        migrations.AddField(
            model_name='citymodel',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='localization.statemodel'),
        ),
    ]
