# Generated by Django 4.2.17 on 2025-02-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localization', '0005_delete_citiesmodel_delete_countriesdialcodemodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citymodel',
            name='latitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='citymodel',
            name='longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='countrymodel',
            name='currency_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='countrymodel',
            name='latitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='countrymodel',
            name='longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='statemodel',
            name='latitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='statemodel',
            name='longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='statemodel',
            name='state_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='timezonemodel',
            name='tz_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='timezonemodel',
            name='zone_name',
            field=models.CharField(max_length=100),
        ),
    ]
