# Generated by Django 4.2.17 on 2025-05-09 10:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('localization', '0006_alter_citymodel_latitude_alter_citymodel_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrymodel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='countrymodel',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='countrymodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='countrymodel',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
