# Generated by Django 4.2.17 on 2025-05-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localization', '0007_countrymodel_created_at_countrymodel_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrymodel',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
