# Generated by Django 4.2.17 on 2025-01-12 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenantemailverificationmodel',
            old_name='token',
            new_name='otp',
        ),
    ]
