# Generated by Django 4.2.17 on 2025-07-31 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenantpreferenceoptionmodeltranslation',
            old_name='text',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='tenantpreferencequestionmodeltranslation',
            old_name='text',
            new_name='title',
        ),
    ]
