# Generated by Django 4.2.17 on 2025-08-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_rename_text_tenantpreferenceoptionmodeltranslation_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantdetailsmodel',
            name='is_google_account',
            field=models.BooleanField(default=False),
        ),
    ]
