# Generated by Django 4.2.17 on 2025-01-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenant", "0002_rename_token_tenantemailverificationmodel_otp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenantdetailsmodel",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
