# Generated by Django 4.2.17 on 2025-01-25 19:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_drinkinghabitmodel_foodhabitmodel_incomerangemodel_and_more"),
        ("localization", "0001_initial"),
        ("tenant", "0003_alter_tenantdetailsmodel_is_active"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TenantAnswerModel",
            new_name="TenantPreferenceAnswerModel",
        ),
        migrations.RenameModel(
            old_name="TenantOptionModel",
            new_name="TenantPreferenceOptionModel",
        ),
        migrations.RenameModel(
            old_name="TenantQuestionModel",
            new_name="TenantPreferenceQuestionModel",
        ),
        migrations.RenameModel(
            old_name="TenantQuestionTypeModel",
            new_name="TenantPreferenceQuestionTypeModel",
        ),
        migrations.CreateModel(
            name="TenantPersonalityDetailsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pet_lover", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="country",
                        to="localization.countriesmodel",
                    ),
                ),
                (
                    "drinking_habit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drinking_habit",
                        to="user.drinkinghabitmodel",
                    ),
                ),
                (
                    "food_habit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationship_status",
                        to="user.foodhabitmodel",
                    ),
                ),
                (
                    "income_range",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="income_range",
                        to="user.incomerangemodel",
                    ),
                ),
                (
                    "occupation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="occupation",
                        to="user.occupationmodel",
                    ),
                ),
                (
                    "relationship_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationship_status",
                        to="user.relationshipstatusmodel",
                    ),
                ),
                (
                    "religion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="religion",
                        to="user.religionmodel",
                    ),
                ),
                (
                    "smoking_habit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="smoking_habit",
                        to="user.smokinghabitmodel",
                    ),
                ),
                (
                    "socializing_habit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="socializing_habit",
                        to="user.socializinghabitmodel",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_personality",
                        to="tenant.tenantdetailsmodel",
                    ),
                ),
            ],
        ),
    ]
