# Generated by Django 4.2.17 on 2025-02-11 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localization', '0004_citymodel_countrymodel_countrytranslationmodel_and_more'),
        ('tenant', '0004_rename_tenantanswermodel_tenantpreferenceanswermodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantpersonalitydetailsmodel',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country', to='localization.countrymodel'),
        ),
    ]
