# Generated by Django 4.2.17 on 2025-02-12 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_drinkinghabitmodel_foodhabitmodel_incomerangemodel_and_more'),
        ('localization', '0006_alter_citymodel_latitude_alter_citymodel_longitude_and_more'),
        ('tenant', '0005_alter_tenantpersonalitydetailsmodel_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantpersonalitydetailsmodel',
            name='country',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='country', to='localization.countrymodel'),
        ),
        migrations.AlterField(
            model_name='tenantpersonalitydetailsmodel',
            name='drinking_habit',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='drinking_habit', to='user.drinkinghabitmodel'),
        ),
        migrations.AlterField(
            model_name='tenantpersonalitydetailsmodel',
            name='food_habit',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='relationship_status', to='user.foodhabitmodel'),
        ),
        migrations.AlterField(
            model_name='tenantpersonalitydetailsmodel',
            name='income_range',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='income_range', to='user.incomerangemodel'),
        ),
        migrations.AlterField(
            model_name='tenantpersonalitydetailsmodel',
            name='occupation',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='occupation', to='user.occupationmodel'),
        ),
        migrations.AlterField(
            model_name='tenantpersonalitydetailsmodel',
            name='relationship_status',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='relationship_status', to='user.relationshipstatusmodel'),
        ),
        migrations.AlterField(
            model_name='tenantpersonalitydetailsmodel',
            name='religion',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='religion', to='user.religionmodel'),
        ),
        migrations.AlterField(
            model_name='tenantpersonalitydetailsmodel',
            name='smoking_habit',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='smoking_habit', to='user.smokinghabitmodel'),
        ),
        migrations.AlterField(
            model_name='tenantpersonalitydetailsmodel',
            name='socializing_habit',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='socializing_habit', to='user.socializinghabitmodel'),
        ),
    ]
