# Generated by Django 4.2.17 on 2025-02-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0007_alter_tenantpersonalitydetailsmodel_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantpersonalitydetailsmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
