# Generated by Django 4.2.17 on 2025-02-12 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localization', '0006_alter_citymodel_latitude_alter_citymodel_longitude_and_more'),
        ('tenant', '0008_alter_tenantpersonalitydetailsmodel_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantdetailsmodel',
            name='preferred_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preferred_city', to='localization.citymodel'),
        ),
    ]
