# Generated by Django 4.2.17 on 2025-02-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0009_tenantdetailsmodel_preferred_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantidentityverificationmodel',
            name='document_file',
            field=models.FileField(upload_to='static/tenant_identity_documents/'),
        ),
    ]
