# Generated by Django 4.2.17 on 2025-02-13 15:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0010_alter_tenantidentityverificationmodel_document_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantidentityverificationmodel',
            name='document_file',
        ),
        migrations.CreateModel(
            name='TenantIdentityVerificationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='static/tenant_identity_documents/')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('identity_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='tenant.tenantidentityverificationmodel')),
            ],
        ),
    ]
