# Generated by Django 4.2.17 on 2025-02-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0011_remove_tenantidentityverificationmodel_document_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantdetailsmodel',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='static/profile_pictures/'),
        ),
    ]
