# Generated by Django 4.2.17 on 2025-02-27 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0001_initial'),
        ('tenant', '0012_alter_tenantdetailsmodel_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantdetailsmodel',
            name='preferred_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preferred_language_tenant', to='translations.languagemodel'),
        ),
    ]
