# Generated by Django 4.2.17 on 2025-03-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0013_tenantdetailsmodel_preferred_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantdetailsmodel',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
