# Generated by Django 4.2.17 on 2025-03-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0014_alter_tenantdetailsmodel_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantidentityverificationmodel',
            name='document_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
