# Generated by Django 4.2.17 on 2025-05-09 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0015_alter_tenantidentityverificationmodel_document_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantdetailsmodel',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
