# Generated by Django 4.2.17 on 2025-01-01 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('language_data', '0001_initial'),
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeningSentencesDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.CharField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_data_base_language', to='language_data.languagemodel')),
                ('learning_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_data_learning_language', to='language_data.languagemodel')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_sentence_data_topic', to='modules.topicmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ListeningStoryDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listening_sentence_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listening_story_data_topic', to='listening_module.listeningsentencesdatamodel')),
            ],
        ),
    ]
