# Generated by Django 4.2.17 on 2025-01-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listening_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeningstorydatamodel',
            name='story',
            field=models.CharField(),
        ),
    ]
