# Generated by Django 4.2.17 on 2025-01-23 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landlord", "0002_landlordemailverificationmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="landlorddetailsmodel",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
