# Generated by Django 4.2.17 on 2025-01-25 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("landlord", "0003_alter_landlorddetailsmodel_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="landlordquestionmodel",
            name="applicable_property_types",
        ),
        migrations.RemoveField(
            model_name="landlordquestionmodel",
            name="property",
        ),
    ]
