# Generated by Django 4.2.17 on 2025-07-31 08:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('landlord', '0003_add_parler_bases'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='landlordoptionmodel',
            options={'ordering': ['-created_at'], 'verbose_name': 'Landlord Question Option', 'verbose_name_plural': 'Landlord Question Options'},
        ),
        migrations.AlterModelOptions(
            name='landlordquestionmodel',
            options={'ordering': ['-created_at'], 'verbose_name': 'Landlord Question', 'verbose_name_plural': 'Landlord Questions'},
        ),
        migrations.RemoveField(
            model_name='landlordoptionmodel',
            name='option_text',
        ),
        migrations.RemoveField(
            model_name='landlordquestionmodel',
            name='question_text',
        ),
        migrations.AddField(
            model_name='landlordidentityverificationfile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='landlordidentityverificationfile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landlordidentityverificationfile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='landlordidentityverificationfile',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='landlordoptionmodel',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='landlord.landlordquestionmodel'),
        ),
        migrations.AlterField(
            model_name='landlordquestionmodel',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_content_type', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='landlordquestionmodel',
            name='question_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='landlord.landlordquestiontypemodel'),
        ),
        migrations.CreateModel(
            name='LandlordQuestionModelTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('question_text', models.TextField()),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='landlord.landlordquestionmodel')),
            ],
            options={
                'verbose_name': 'Landlord Question Translation',
                'db_table': 'landlord_landlordquestionmodel_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LandlordOptionModelTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('option_text', models.CharField(max_length=255)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='landlord.landlordoptionmodel')),
            ],
            options={
                'verbose_name': 'Landlord Question Option Translation',
                'db_table': 'landlord_landlordoptionmodel_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
