# Generated by Django 4.2.17 on 2025-07-31 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0004_alter_landlordoptionmodel_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landlordoptionmodeltranslation',
            old_name='option_text',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='landlordquestionmodeltranslation',
            old_name='question_text',
            new_name='title',
        ),
    ]
