# Generated by Django 4.2.17 on 2025-01-27 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        (
            "landlord",
            "0004_remove_landlordquestionmodel_applicable_property_types_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="landlordanswermodel",
            name="option",
        ),
        migrations.RemoveField(
            model_name="landlordanswermodel",
            name="priority",
        ),
        migrations.RemoveField(
            model_name="landlordanswermodel",
            name="static_option",
        ),
        migrations.AddField(
            model_name="landlordanswermodel",
            name="content_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="content_type",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="landlordanswermodel",
            name="object_id",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="landlordanswermodel",
            name="preference",
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
