# Generated by Django 4.2.17 on 2025-01-27 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("landlord", "0005_remove_landlordanswermodel_option_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="landlordquestionmodel",
            name="content_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question_content_type",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="landlordanswermodel",
            name="preference",
            field=models.IntegerField(null=True),
        ),
    ]
