# Generated by Django 4.2.17 on 2025-08-01 09:15

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0006_translate_property_type_amenities_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landlordpropertyamenitymodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='landlordpropertyamenitymodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='landlordpropertytypemodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='landlordpropertytypemodel',
            name='type_name',
        ),
        migrations.CreateModel(
            name='LandlordPropertyTypeModelTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('type_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='landlord.landlordpropertytypemodel')),
            ],
            options={
                'verbose_name': 'landlord property type model Translation',
                'db_table': 'landlord_landlordpropertytypemodel_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LandlordPropertyAmenityModelTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='landlord.landlordpropertyamenitymodel')),
            ],
            options={
                'verbose_name': 'landlord property amenity model Translation',
                'db_table': 'landlord_landlordpropertyamenitymodel_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
