# Generated by Django 4.2.17 on 2025-01-28 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("landlord", "0006_landlordquestionmodel_content_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="landlordanswermodel",
            name="bed",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="room_wise_bed",
                to="landlord.landlordroomwisebedmodel",
            ),
        ),
    ]
