# Generated by Django 4.2.17 on 2025-01-28 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("landlord", "0007_alter_landlordanswermodel_bed"),
    ]

    operations = [
        migrations.AddField(
            model_name="landlordanswermodel",
            name="landlord",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="landlord_details",
                to="landlord.landlorddetailsmodel",
            ),
        ),
    ]
