# Generated by Django 4.2.17 on 2025-08-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0007_remove_landlordpropertyamenitymodel_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlorddetailsmodel',
            name='is_google_account',
            field=models.BooleanField(default=False),
        ),
    ]
