# Generated by Django 4.2.17 on 2025-02-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landlord", "0008_landlordanswermodel_landlord"),
    ]

    operations = [
        migrations.AddField(
            model_name="landlordroomwisebedmodel",
            name="bed_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
