# Generated by Django 4.2.17 on 2025-02-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landlord", "0009_landlordroomwisebedmodel_bed_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="landlordroomwisebedmodel",
            name="bed_images",
            field=models.ImageField(blank=True, null=True, upload_to="bed_images/"),
        ),
        migrations.AddField(
            model_name="landlordroomwisebedmodel",
            name="bed_videos",
            field=models.FileField(blank=True, null=True, upload_to="bed_videos/"),
        ),
    ]
