# Generated by Django 4.2.17 on 2025-02-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landlord", "0010_landlordroomwisebedmodel_bed_images_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="landlordpropertyroomdetailsmodel",
            name="room_images",
            field=models.ImageField(blank=True, null=True, upload_to="room_images/"),
        ),
        migrations.AddField(
            model_name="landlordpropertyroomdetailsmodel",
            name="room_videos",
            field=models.FileField(blank=True, null=True, upload_to="room_videos/"),
        ),
    ]
