# Generated by Django 4.2.17 on 2025-02-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landlord", "0011_landlordpropertyroomdetailsmodel_room_images_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="landlorddetailsmodel",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="static/profile_pictures/"
            ),
        ),
        migrations.AlterField(
            model_name="landlordidentityverificationmodel",
            name="document_file",
            field=models.FileField(upload_to="static/landlord_identity_documents/"),
        ),
        migrations.AlterField(
            model_name="landlordpropertydetailsmodel",
            name="property_images",
            field=models.ImageField(
                blank=True, null=True, upload_to="static/property_images/"
            ),
        ),
        migrations.AlterField(
            model_name="landlordpropertydetailsmodel",
            name="property_videos",
            field=models.FileField(
                blank=True, null=True, upload_to="static/property_videos/"
            ),
        ),
        migrations.AlterField(
            model_name="landlordpropertyroomdetailsmodel",
            name="room_images",
            field=models.ImageField(
                blank=True, null=True, upload_to="static/room_images/"
            ),
        ),
        migrations.AlterField(
            model_name="landlordpropertyroomdetailsmodel",
            name="room_videos",
            field=models.FileField(
                blank=True, null=True, upload_to="static/room_videos/"
            ),
        ),
        migrations.AlterField(
            model_name="landlordpropertyverificationmodel",
            name="document_file",
            field=models.FileField(upload_to="static/property_verification_documents/"),
        ),
        migrations.AlterField(
            model_name="landlordroomwisebedmodel",
            name="bed_images",
            field=models.ImageField(
                blank=True, null=True, upload_to="static/bed_images/"
            ),
        ),
        migrations.AlterField(
            model_name="landlordroomwisebedmodel",
            name="bed_videos",
            field=models.FileField(
                blank=True, null=True, upload_to="static/bed_videos/"
            ),
        ),
    ]
