# Generated by Django 4.2.17 on 2025-02-03 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("landlord", "0012_alter_landlorddetailsmodel_profile_picture_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="landlordpropertydetailsmodel",
            name="property_images",
        ),
        migrations.RemoveField(
            model_name="landlordpropertydetailsmodel",
            name="property_videos",
        ),
        migrations.RemoveField(
            model_name="landlordpropertyroomdetailsmodel",
            name="room_images",
        ),
        migrations.RemoveField(
            model_name="landlordpropertyroomdetailsmodel",
            name="room_videos",
        ),
        migrations.RemoveField(
            model_name="landlordroomwisebedmodel",
            name="bed_images",
        ),
        migrations.RemoveField(
            model_name="landlordroomwisebedmodel",
            name="bed_videos",
        ),
        migrations.CreateModel(
            name="LandlordRoomMediaModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="static/room_media/")),
                (
                    "media_type",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Video")], max_length=10
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_media",
                        to="landlord.landlordpropertyroomdetailsmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LandlordPropertyMediaModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="static/property_media/")),
                (
                    "media_type",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Video")], max_length=10
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_media",
                        to="landlord.landlordpropertydetailsmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LandlordBedMediaModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="static/bed_media/")),
                (
                    "media_type",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Video")], max_length=10
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "bed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bed_media",
                        to="landlord.landlordroomwisebedmodel",
                    ),
                ),
            ],
        ),
    ]
