# Generated by Django 4.2.17 on 2025-02-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "landlord",
            "0013_remove_landlordpropertydetailsmodel_property_images_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="landlordroomwisebedmodel",
            name="availability_end_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="landlordroomwisebedmodel",
            name="availability_start_date",
            field=models.DateField(null=True),
        ),
    ]
