# Generated by Django 4.2.17 on 2025-02-05 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "landlord",
            "0014_alter_landlordroomwisebedmodel_availability_end_date_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="landlordanswermodel",
            name="bed",
        ),
        migrations.AddField(
            model_name="landlordroomwisebedmodel",
            name="tenant_preference_answers",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tenant_preference_answers",
                to="landlord.landlordanswermodel",
            ),
        ),
        migrations.AddField(
            model_name="landlordroomwisebedmodel",
            name="tenant_preference_same_as",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="landlordpropertyroomdetailsmodel",
            name="room_size",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="landlordpropertyroomdetailsmodel",
            name="room_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="room_type",
                to="landlord.landlordpropertyroomtypemodel",
            ),
        ),
    ]
