# Generated by Django 4.2.17 on 2025-02-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landlord", "0015_remove_landlordanswermodel_bed_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="landlordroomwisebedmodel",
            name="tenant_preference_answers",
        ),
        migrations.AddField(
            model_name="landlordroomwisebedmodel",
            name="tenant_preference_answers",
            field=models.ManyToManyField(
                null=True,
                related_name="tenant_preference_answers",
                to="landlord.landlordanswermodel",
            ),
        ),
    ]
