# Generated by Django 4.2.17 on 2025-02-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "landlord",
            "0016_remove_landlordroomwisebedmodel_tenant_preference_answers_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="landlordroomwisebedmodel",
            name="tenant_preference_answers",
            field=models.ManyToManyField(
                related_name="tenant_preference_answers",
                to="landlord.landlordanswermodel",
            ),
        ),
    ]
