# Generated by Django 4.2.17 on 2025-02-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landlord", "0017_alter_landlordroomwisebedmodel_tenant_preference_answers"),
    ]

    operations = [
        migrations.AddField(
            model_name="landlordroomwisebedmodel",
            name="sameAsBedIndex",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="landlordroomwisebedmodel",
            name="sameAsRoomIndex",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
