# Generated by Django 4.2.17 on 2025-02-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0018_landlordroomwisebedmodel_sameasbedindex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlordroomwisebedmodel',
            name='sameAsBedIndex',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='landlordroomwisebedmodel',
            name='sameAsRoomIndex',
            field=models.IntegerField(null=True),
        ),
    ]
