# Generated by Django 4.2.17 on 2025-02-11 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localization', '0003_countriesmodel_currency_countriesmodel_currency_name_and_more'),
        ('landlord', '0019_alter_landlordroomwisebedmodel_sameasbedindex_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlordpropertydetailsmodel',
            name='property_city',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='localization.citiesmodel'),
        ),
    ]
