# Generated by Django 4.2.17 on 2025-02-11 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localization', '0004_citymodel_countrymodel_countrytranslationmodel_and_more'),
        ('landlord', '0020_landlordpropertydetailsmodel_property_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlordpropertydetailsmodel',
            name='property_city',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='localization.citymodel'),
        ),
    ]
