# Generated by Django 4.2.17 on 2025-02-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0021_alter_landlordpropertydetailsmodel_property_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlordpropertydetailsmodel',
            name='pin_code',
            field=models.TextField(default=''),
        ),
    ]
