# Generated by Django 4.2.17 on 2025-02-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0022_landlordpropertydetailsmodel_pin_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlordroomwisebedmodel',
            name='availability_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='landlordroomwisebedmodel',
            name='availability_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='landlordroomwisebedmodel',
            name='is_available',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='landlordroomwisebedmodel',
            name='sameAsBedIndex',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='landlordroomwisebedmodel',
            name='sameAsRoomIndex',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='landlordroomwisebedmodel',
            name='tenant_preference_same_as',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
