# Generated by Django 4.2.17 on 2025-02-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0023_alter_landlordroomwisebedmodel_availability_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landlordroomwisebedmodel',
            old_name='rent_per_month',
            new_name='rent_amount',
        ),
        migrations.RemoveField(
            model_name='landlordroomwisebedmodel',
            name='availability_end_date',
        ),
        migrations.AddField(
            model_name='landlordroomwisebedmodel',
            name='agreement_duration_monthly',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landlordroomwisebedmodel',
            name='is_rent_monthly',
            field=models.BooleanField(default=True),
        ),
    ]
