# Generated by Django 4.2.17 on 2025-02-15 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0024_rename_rent_per_month_landlordroomwisebedmodel_rent_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landlordroomwisebedmodel',
            old_name='agreement_duration_monthly',
            new_name='min_agreement_duration_in_months',
        ),
    ]
