# Generated by Django 4.2.17 on 2025-02-18 17:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0012_alter_tenantdetailsmodel_profile_picture'),
        ('landlord', '0025_rename_agreement_duration_monthly_landlordroomwisebedmodel_min_agreement_duration_in_months'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantInterestRequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_interest_requests', to='landlord.landlordpropertydetailsmodel')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_interest_requests', to='tenant.tenantdetailsmodel')),
            ],
        ),
    ]
