# Generated by Django 4.2.17 on 2025-02-18 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0026_tenantinterestrequestmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantinterestrequestmodel',
            name='property',
        ),
        migrations.AddField(
            model_name='tenantinterestrequestmodel',
            name='bed',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tenant_interest_requests_for_bed', to='landlord.landlordroomwisebedmodel'),
        ),
    ]
