# Generated by Django 4.2.17 on 2025-02-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0027_remove_tenantinterestrequestmodel_property_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantinterestrequestmodel',
            name='landlord_message',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
