# Generated by Django 4.2.17 on 2025-02-21 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0028_tenantinterestrequestmodel_landlord_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TenantInterestRequestModel',
        ),
    ]
