# Generated by Django 4.2.17 on 2025-02-23 16:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0029_delete_tenantinterestrequestmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LandlordPropertyVerificationDocumentTypeModel',
            new_name='LandlordDocumentTypeModel',
        ),
        migrations.RemoveField(
            model_name='landlordidentityverificationmodel',
            name='document_file',
        ),
        migrations.CreateModel(
            name='LandlordIdentityVerificationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='static/landlord_identity_documents/')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('identity_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='landlord.landlordidentityverificationmodel')),
            ],
        ),
    ]
