# Generated by Django 4.2.17 on 2025-02-27 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0001_initial'),
        ('landlord', '0030_rename_landlordpropertyverificationdocumenttypemodel_landlorddocumenttypemodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlorddetailsmodel',
            name='preferred_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preferred_language_landlord', to='translations.languagemodel'),
        ),
    ]
