# Generated by Django 4.2.17 on 2025-03-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0031_landlorddetailsmodel_preferred_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlordbedmediamodel',
            name='file',
            field=models.FileField(upload_to='bed_media/'),
        ),
        migrations.AlterField(
            model_name='landlordpropertymediamodel',
            name='file',
            field=models.FileField(upload_to='property_media/'),
        ),
        migrations.AlterField(
            model_name='landlordroommediamodel',
            name='file',
            field=models.FileField(upload_to='room_media/'),
        ),
    ]
