# Generated by Django 4.2.17 on 2025-03-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0032_alter_landlordbedmediamodel_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landlordroomwisebedmodel',
            name='sameAsBedIndex',
        ),
        migrations.RemoveField(
            model_name='landlordroomwisebedmodel',
            name='sameAsRoomIndex',
        ),
        migrations.AddField(
            model_name='landlordpropertyroomdetailsmodel',
            name='same_as_room_id',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AddField(
            model_name='landlordroomwisebedmodel',
            name='same_as_bed_id',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
    ]
