# Generated by Django 4.2.17 on 2025-03-04 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("landlord", "0033_remove_landlordroomwisebedmodel_sameasbedindex_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="landlordpropertyroomdetailsmodel",
            name="same_as_room_id",
        ),
        migrations.RemoveField(
            model_name="landlordroomwisebedmodel",
            name="same_as_bed_id",
        ),
        migrations.RemoveField(
            model_name="landlordroomwisebedmodel",
            name="tenant_preference_same_as",
        ),
    ]
