# Generated by Django 4.2.17 on 2025-03-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0034_remove_landlordpropertyroomdetailsmodel_same_as_room_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlorddetailsmodel',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
