# Generated by Django 4.2.17 on 2025-04-23 04:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0035_alter_landlorddetailsmodel_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandlordBasePreferenceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answers', models.ManyToManyField(blank=True, related_name='base_preference_sets', to='landlord.landlordanswermodel')),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_preferences', to='landlord.landlorddetailsmodel')),
            ],
            options={
                'unique_together': {('landlord',)},
            },
        ),
    ]
