# Generated by Django 4.2.17 on 2025-04-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0036_landlordbasepreferencemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlordroomwisebedmodel',
            name='tenant_preference',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
