# Generated by Django 4.2.17 on 2025-04-25 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0037_landlordroomwisebedmodel_tenant_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlordroomwisebedmodel',
            name='tenant_preference',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
    ]
