# Generated by Django 4.2.17 on 2025-05-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0038_alter_landlordroomwisebedmodel_tenant_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlordpropertyroomdetailsmodel',
            name='room_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
