# Generated by Django 4.2.17 on 2025-05-09 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0039_landlordpropertyroomdetailsmodel_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlorddetailsmodel',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
