# Generated by Django 4.2.17 on 2025-05-11 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0040_landlorddetailsmodel_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlordpropertydetailsmodel',
            name='street_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
