# Generated by Django 4.2.17 on 2025-05-11 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0041_landlordpropertydetailsmodel_street_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlordpropertydetailsmodel',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='landlordpropertydetailsmodel',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
    ]
