# Generated by Django 4.2.17 on 2025-05-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0042_alter_landlordpropertydetailsmodel_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlordpropertyroomdetailsmodel',
            name='current_female_occupants',
            field=models.PositiveIntegerField(default=0, help_text='Current number of female-identifying occupants', verbose_name='Number of female occupants'),
        ),
        migrations.AddField(
            model_name='landlordpropertyroomdetailsmodel',
            name='current_male_occupants',
            field=models.PositiveIntegerField(default=0, help_text='Current number of male-identifying occupants', verbose_name='Number of male occupants'),
        ),
    ]
