# Generated by Django 4.2.17 on 2025-07-09 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('landlord', '0043_landlordpropertyroomdetailsmodel_current_female_occupants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlorddetailsmodel',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='landlord', to=settings.AUTH_USER_MODEL),
        ),
    ]
