# Generated by Django 4.2.17 on 2025-07-09 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0044_landlorddetailsmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landlorddetailsmodel',
            name='user',
        ),
    ]
