# Generated by Django 4.2.17 on 2025-05-13 12:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant', '0016_tenantdetailsmodel_last_login'),
        ('landlord', '0042_alter_landlordpropertydetailsmodel_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantSupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('inprogress', 'In Progress'), ('closed', 'Closed')], default='open', max_length=10)),
                ('admin_comment', models.TextField(blank=True, help_text='Internal notes or replies from support team')),
                ('updated_by', models.CharField(default='tenant', help_text="who last updated: 'tenant'|'admin'", max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to='tenant.tenantdetailsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='LandlordSupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('inprogress', 'In Progress'), ('closed', 'Closed')], default='open', max_length=10)),
                ('admin_comment', models.TextField(blank=True, help_text='Internal notes or replies from support team')),
                ('updated_by', models.CharField(default='landlord', help_text="who last updated: 'landlord'|'admin'", max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to='landlord.landlorddetailsmodel')),
            ],
        ),
    ]
