# Generated by Django 4.2.17 on 2025-08-01 12:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import parler.fields
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant', '0002_rename_text_tenantpreferenceoptionmodeltranslation_title_and_more'),
        ('landlord', '0007_remove_landlordpropertyamenitymodel_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestRequestStatusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TenantInterestRequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landlord_message', models.CharField(blank=True, default='', max_length=50)),
                ('request_closed_by', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('bed', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tenant_interest_requests_for_bed', to='landlord.landlordroomwisebedmodel')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_requests', to='interest_requests.interestrequeststatusmodel')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_interest_requests', to='tenant.tenantdetailsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='LandlordInterestRequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_message', models.CharField(blank=True, default='', max_length=50)),
                ('request_closed_by', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('bed', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='landlord_interest_requests_from_bed', to='landlord.landlordroomwisebedmodel')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='landlord_requests', to='interest_requests.interestrequeststatusmodel')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landlord_interest_requests', to='tenant.tenantdetailsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='InterestRequestStatusModelTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('label', models.CharField(max_length=50)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='interest_requests.interestrequeststatusmodel')),
            ],
            options={
                'verbose_name': 'interest request status model Translation',
                'db_table': 'interest_requests_interestrequeststatusmodel_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
