# Generated by Django 4.2.17 on 2025-02-21 16:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant', '0012_alter_tenantdetailsmodel_profile_picture'),
        ('landlord', '0029_delete_tenantinterestrequestmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantInterestRequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('landlord_message', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('bed', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tenant_interest_requests_for_bed', to='landlord.landlordroomwisebedmodel')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_interest_requests', to='tenant.tenantdetailsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='LandlordInterestRequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('tenant_message', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('bed', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='landlord_interest_requests_from_bed', to='landlord.landlordroomwisebedmodel')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landlord_interest_requests', to='tenant.tenantdetailsmodel')),
            ],
        ),
    ]
