# Generated by Django 4.2.17 on 2025-02-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interest_requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlordinterestrequestmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('block', 'block')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='tenantinterestrequestmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('block', 'block')], default='pending', max_length=10),
        ),
    ]
