# Generated by Django 4.2.17 on 2025-02-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interest_requests', '0002_alter_landlordinterestrequestmodel_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlordinterestrequestmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='tenantinterestrequestmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
