# Generated by Django 4.2.17 on 2025-02-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interest_requests', '0003_alter_landlordinterestrequestmodel_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlordinterestrequestmodel',
            name='request_closed_by',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='tenantinterestrequestmodel',
            name='request_closed_by',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='landlordinterestrequestmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='tenantinterestrequestmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='pending', max_length=10),
        ),
    ]
