# Generated by Django 4.2.17 on 2025-02-26 11:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant', '0012_alter_tenantdetailsmodel_profile_picture'),
        ('landlord', '0030_rename_landlordpropertyverificationdocumenttypemodel_landlorddocumenttypemodel_and_more'),
        ('landlord_availability', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentBookingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bed_appointments', to='landlord.landlordroomwisebedmodel')),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landlord_appointments', to='landlord.landlorddetailsmodel')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_appointments', to='tenant.tenantdetailsmodel')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_appointments', to='landlord_availability.landlordavailabilityslotmodel')),
            ],
            options={
                'verbose_name': 'Appointment Booking',
                'verbose_name_plural': 'Appointment Bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
