# Generated by Django 4.2.17 on 2025-07-31 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentbookingmodeltranslation',
            old_name='status_label',
            new_name='title',
        ),
    ]
