# Generated by Django 4.2.17 on 2025-05-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointmentbookingmodel_initiated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentbookingmodel',
            name='last_updated_by',
            field=models.CharField(choices=[('tenant', 'Tenant'), ('landlord', 'Landlord')], default='tenant', max_length=10),
        ),
        migrations.AlterField(
            model_name='appointmentbookingmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
    ]
