# Generated by Django 4.2.17 on 2025-01-11 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('language_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceToFaceConversationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcription', models.TextField(blank=True, null=True)),
                ('translation', models.TextField(blank=True, null=True)),
                ('suggested_response_preferred', models.TextField(blank=True, null=True)),
                ('suggested_response_learning', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('learning_language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_language_conversations', to='language_data.languagemodel')),
                ('learning_language_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_level_conversations', to='language_data.languagelevelmodel')),
                ('preferred_language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_language_conversations', to='language_data.languagemodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_to_face_conversations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
