# Generated by Django 4.2.17 on 2025-01-11 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('speaking_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facetofaceconversationmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_to_face_conversations', to='users.usermodel'),
        ),
    ]
