# Generated by Django 4.2.17 on 2025-05-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_otpmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='role_name',
            field=models.CharField(choices=[('tenant', 'Tenant'), ('landlord', 'Landlord')], max_length=20),
        ),
    ]
