# Generated by Django 4.2.17 on 2025-02-27 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_rename_devicenotification_devicenotificationmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicenotificationmodel',
            name='player_id',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
