# Generated by Django 4.2.17 on 2025-05-16 16:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0042_alter_landlordpropertydetailsmodel_latitude_and_more'),
        ('tenant', '0016_tenantdetailsmodel_last_login'),
        ('notifications', '0003_alter_devicenotificationmodel_player_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandlordDeviceNotificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_notifications', to='landlord.landlorddetailsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='LandlordNotificationSettingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to='landlord.landlorddetailsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Machine‐readable code, e.g. 'tenant_request', 'chat_message'", max_length=50, unique=True)),
                ('name', models.CharField(help_text='Human‐readable name', max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TenantDeviceNotificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_notifications', to='tenant.tenantdetailsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='TenantNotificationSettingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_settings', to='notifications.notificationtypemodel')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to='tenant.tenantdetailsmodel')),
            ],
            options={
                'unique_together': {('tenant', 'notification_type')},
            },
        ),
        migrations.DeleteModel(
            name='DeviceNotificationModel',
        ),
        migrations.AddField(
            model_name='landlordnotificationsettingmodel',
            name='notification_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landlord_settings', to='notifications.notificationtypemodel'),
        ),
        migrations.AlterUniqueTogether(
            name='landlordnotificationsettingmodel',
            unique_together={('landlord', 'notification_type')},
        ),
    ]
